Add support for capturing resource usage during test execution. (#527)
Adds `+stats-report` and `+stats-graph` arguments to act-wrapper.

Also changes act-wrapper to exit with the exit code of act instead of suppressing it.

---------

Co-authored-by: Jannik Peters <jannik@nlnetlabs.nl>

diff --git a/act-wrapper b/act-wrapper
--- a/act-wrapper
+++ b/act-wrapper
@@ -2,7 +2,7 @@
 
 set -e
 
-if [[ "$1" =~ ^-h|--help$ ]]; then
+function usage {
 	echo "The act wrapper script."
 	echo
 	echo "This script first builds the container image for running the tests"
@@ -18,12 +18,26 @@ if [[ "$1" =~ ^-h|--help$ ]]; then
 	echo
 	echo "'$0 +build-inside <act-args>'"
 	echo
-	echo "(NOTE: '+nobuild' or '+build-inside' MUST be the first argument to"
-	echo "the act-wrapper)"
+	echo "If you want to produce a report of approximate CPU and memory usage"
+	echo "over time use:"
+	echo
+	echo "'$0 +stats-report </path/to/write/report.csv>'"
+	echo
+	echo "To create a PNG graph of the usage use: (requires gnuplot)"
+	echo "Note: If +stats-report is not used, a temporary file will be used"
+	echo "to capture resource usage in CSV format."
+	echo
+	echo "'$0 +stats-graph </path/to/write/report.png>'"
+	echo
+	echo "NOTE: '+XXX' arguments must be the first arguments to act-wrapper, and can be combined."
 	echo
 	echo "Inputs that can be provided via --input:"
-	echo "  --input build-profile=debug|release"
-	echo "  --input log-level=error|warn|info|debug|trace"
+	echo "	--input build-profile=debug|release"
+	echo "	--input log-level=error|warn|info|debug|trace"
+}
+
+if [[ "$1" =~ ^-h|--help$ ]]; then
+	usage
 	exit
 fi
 
@@ -60,6 +74,21 @@ while [[ "$1" =~ ^\+ ]]; do
 		+nobuild)
 			no_build=true
 			;;
+		+stats-report)
+			docker_stats=true
+			shift
+			docker_stats_path="$1"
+			;;
+		+stats-graph)
+			docker_stats_graph=true
+			shift
+			docker_stats_graph_path="$1"
+			;;
+		*)
+			echo >&2 "ERROR: Unrecognized + argument: $1"
+			usage
+			exit
+		 ;;
 	esac
 	shift
 done
@@ -74,9 +103,124 @@ if [[ "$no_build" != true ]]; then
 	echo "Built Cascade integration test runner based on local repository."
 fi
 
-act "${act_args[@]}" --pull=false -P "ubuntu-latest=nlnetlabs/cascade-tests-runner" -W integration-tests/system-tests.yml "$@" || true
+if [[ "$docker_stats_graph" == true && "$docker_stats" != true ]]; then
+	docker_stats=true
+	docker_stats_path=$(mktemp)
+fi
+
+if [[ "$docker_stats" == true ]]; then
+	# Only collect docker stats if no other Docker containers are already running.
+	NUM_DOCKER_CONTAINERS_RUNNING=$(docker ps -q | wc -l)
+	if [[ "${NUM_DOCKER_CONTAINERS_RUNNING}" -gt 0 ]]; then
+		echo >&2 "ERROR: Can only collect Docker statistics reliably if there are no other containers running."
+		exit 1
+	fi
+
+	echo "Logging Docker approximate CPU and memory usage to '${docker_stats_path}'."
+
+	# Delete previous report file.
+	[ -f "${docker_stats_path}" ] && rm "${docker_stats_path}"
+
+	# Capture usage via docker stats in the background.
+	(
+		echo "Timestamp,CPU %,Memory Usage Bytes" >> "${docker_stats_path}"
+		while true; do
+			NOW=$(date +"%s")
+
+			# Convert XiB values (KiB, MiB, GiB) to their bytes equivalent using
+			# 'numfmt'. numfmt understands Ki, Mi, Gi, but not the trailing 'B' so
+			# we strip that out.
+			RAW=$(docker stats --format "${NOW}, {{.CPUPerc}}, {{.MemUsage}}" --no-stream)
+
+			# Don't attempt to monitor usage by multiple containers at once, this
+			# functionality is only intended for the simple case of a single test
+			# running inside a single container.
+			NUM_LINES=$(echo "${RAW}" | wc -l)
+			if [[ "${NUM_LINES}" -gt 1 ]]; then
+				# We will detect below that this process has unexpectedly terminated.
+				exit 1
+			fi
+
+			# Skip empty lines.
+			if [[ "${RAW}" != "" && $RAW != *"--"* ]]; then
+				TIMESTAMP=$(echo "${RAW}" | cut -d ',' -f 1)
+				CPU=$(echo "${RAW}" | cut -d ',' -f 2)
+				MEMORY=$(echo "${RAW}" | cut -d ',' -f 3)
+				MEMORY_CURRENT_BYTES=$(echo "${MEMORY}" | cut -d '/' -f 1 | tr -d 'B' | numfmt --from=auto || echo "0")
+				FORMATTED="${TIMESTAMP}, ${CPU}, ${MEMORY_CURRENT_BYTES}"
+				echo "${FORMATTED}" >>"${docker_stats_path}"
+			fi
+		done
+	) &
+
+	# Note the PID of the background shell so that we can stop it after act
+	# finishes running.
+	STATS_PID=$!
+	echo "Docker stats being collected by PID ${STATS_PID}."
+fi
+
+echo "Running tests"
+act "${act_args[@]}" --pull=false -P "ubuntu-latest=nlnetlabs/cascade-tests-runner" -W integration-tests/system-tests.yml "$@" && ACT_EXIT_CODE=$? || ACT_EXIT_CODE=$? 
+
+# Stop the docker stats collection process, if needed.
+if [[ "$docker_stats" == true ]]; then
+	if kill "$STATS_PID" &>/dev/null; then
+		STATS_OKAY=true
+	else
+		echo >&2 "ERROR: Usage statistics could not be collected, perhaps because more than one test was running at once?"
+		rm "${docker_stats_path}" || true
+	fi
+fi
+
+# Generate a gnuplot graph of the stats data, if requested, if stats are
+# available and if the executed tests succeeded.
+if [[ "${docker_stats_graph}" == true && "${STATS_OKAY}" == true && "${ACT_EXIT_CODE}" -eq 0 ]]; then
+	if ! command -v gnuplot &>/dev/null; then
+		echo >&2 "ERROR: Skipping resource usage graph generation: gnuplot not available."
+	else
+		# Include the git ref in the chart.
+		GIT_VER=$(git describe --long --dirty)
+
+		# Get the CPU info.
+		CPU_INFO="$(grep 'model name' /proc/cpuinfo | head -n 1 | cut -d ':' -f 2)"
+
+		NUM_LINES=$(wc -l "${docker_stats_path}" | awk '{print $1}')
+		if [[ "${NUM_LINES}" -gt 1 ]]; then
+			echo "Generating usage graph in ${docker_stats_graph_path}"
+
+			# Generate the gnuplot control script.	
+			GNUPLOT_SCRIPT=$(cat <<EOF
+set locale "en_GB.UTF-8"
+set terminal png size 2048,1536
+set datafile separator ','
+set title "Cascade ${GIT_VER}\n{/*0.75 $*}\n{/*0.75 ${CPU_INFO}"
+set timefmt "%s"
+set xdata time
+set format x "%H:%M:%S"
+set format y2 "%.1b %B"
+set ytics nomirror
+set y2tics
+# Tell gnuplot to initially determine labels from the first line of CSV data
+# but then override the labels it will use. This is done to get gnuplot to not
+# treat the first line of CSV as data while still having different CSV column
+# headers than the labels to be used in the graph.
+set key autotitle columnhead
+set xlabel "Time"
+set ylabel "CPU %"
+set y2label "Memory"
+plot "${docker_stats_path}" using 1:2 with lines title "CPU %", '' using 1:3 with lines axis x1y2 title "Memory"
+EOF
+			)
+
+			# Invoke gnuplot to generate the graph.
+			echo "${GNUPLOT_SCRIPT}" | gnuplot -c /dev/stdin > "${docker_stats_graph_path}"
+		fi
+	fi
+fi
 
 if docker container ls --format '{{.Names}}' --all | grep -q "^act-"; then
 	echo "NOTE: act seemingly failed to clean up all containers it created."
 	echo "You may wish to check and clean up lingering containers"
 fi
+
+exit "${ACT_EXIT_CODE}"
